name: CI

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-node@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: check if it works
      run: |
        python ./actions/checkPrTitleForWIP.py
