name: CI

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [10, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: check for WIP in PR HEADING
      uses: peter-evans/commit-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown**
          - Created by [commit-comment][1]

          [1]: https://github.com/peter-evans/commit-comment
        #run: | 
            #npm i @actions/core@^1.0.0 @actions/github@^1.0.0
            #node ./actions/checkPrTitleForWIP.ts
