name: CI

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [10, 12]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        version: ${{ matrix.node_version }}

    - name: check for WIP in PR HEADING
      run: |
        node ./actions/checkPrTitleForWIP.ts
